### ISSUE TITLE
OXPs/OXZ page doesn't show available expansions

### ISSUE THREAD

**Issue by mhsdeveloper** [HiranChaudhuri/OoliteStarter#13]
**Describe the bug**
The tab is stuck showing only the installed expansions. Change the filter and regex doesn't affect the list. Also, clicking reload doesn't work either.

**To Reproduce**
Just load the app and go to the expansion.

**Expected behavior**
The first time I used it it works as expected.

**Screenshots**
![image](https://github.com/HiranChaudhuri/OoliteStarter/assets/34515882/434f21c4-cd3f-48e5-9fc6-a4764df72069)

**Environment (please complete the following information):**
 - OS: Ubuntu (POP OS) 22.04
 - Java version not sure
 - OoliteStarter version  0.1.21-elul.5

**Comment by HiranChaudhuri** [comment]
Could you provide the logfile? It is located in $HOME/.Oolite/Logs

**Comment by HiranChaudhuri** [comment]
Hint: This may have been fixed in https://github.com/HiranChaudhuri/OoliteStarter/releases/tag/v0.1.21-elul.6 meanwhile

**Comment by mhsdeveloper** [comment]
Here ya go. I'll try the latest version and let you know.

thanks,

-bb
________________________________

**Comment by HiranChaudhuri** [comment]
Thank you for the feedback. :-)
